### ISSUE TITLE
Improve Value Set Downloading

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-dashboard#16]
Currently, you need to run `node src/services/valuesets/updateValueSetDb.mjs [your_api_key]` from the root of ccsm-cds-dashboard to download the valuesets from VSAC into [src/services/valusets/valueset-db.js](https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/blob/pilot/src/services/valuesets/valueset-db.js).

We should probably make that command into an npm script that could either read in the api key from an environment variable or prompt the user to enter one, and then add documentation for this step to the ReadMe.

**Comment by yunwwang** [comment]
the command is already in the package.json

   "download-value-sets": "node src/services/valuesets/updateValueSetDb.mjs $UMLS_API_KEY",
 
You can  run `npm run download-valuesets [UMLS_API_KEY]"

**Comment by mickohanlon23** [comment]
Whoops, I completely missed that, thanks! It may be helpful to add a note about this to the README, since this step would be required for any CDS that uses value sets from VSAC.

**Comment by mickohanlon23** [comment]
Whoops, I completely missed that, thanks! It may be helpful to add a note about this to the README, since this step would be required for any CDS that uses value sets from VSAC.

**Comment by mickohanlon23** [comment]
Instructions for downloading value sets from VSAC added to README.md in https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/pull/19.
