### ISSUE TITLE
Add toggle buttons to dashboard

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-dashboard#7]
We have mock-ups for the dashboard UI that include toggle switches for data elements that we don't expect to be easily accessible among our pilot sites.

We should create a component in our Dashboard app to handle this toggling and update the recommendation accordingly.

This can operate similarly to how the code currently handles questionnaire inputs: https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/blob/main/src/services/fhir/resourceConverter.js.

**Comment by mickohanlon23** [comment]
See Jira [CCSMCDS-12](https://jira.mitre.org/browse/CCSMCDS-12) for more details.

**Comment by mrnosal** [comment]
See https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/tree/pilot-toggle-switches for UI which includes the toggle switches. They are not yet connected to add/remove resources

**Comment by mickohanlon23** [comment]
Toggle switches have been connected to the backend within PR https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/pull/32.
