### ISSUE TITLE
Map Observation valueStrings to valueCodes

### ISSUE THREAD

**Issue by mickohanlon23** [ccsm-cds-tools/ccsm-cds-dashboard#9]
Create capability to map Cytology and HrHPV observations that come back with text results into a resource with the appropriate SNOMED coded result.

**Comment by gmmeadows** [comment]
[Here is the link to the mappings](https://mitre.sharepoint.com/:x:/r/sites/CervicalCancerCDS/Shared%20Documents/Pilot%20Task/UMMC%20Pilot/UMMC%20Data%20Mapping/Lab%20Test%20and%20Result%20Mapping/UMMC%20Lab%20Mappings.xlsx?d=w358d894df255428785601d4a3b923f45&csf=1&web=1&e=a8OLpJ). The first tab explains all the subsequent tabs. Please let me know if you have questions.

**Comment by mickohanlon23** [comment]
At some point between when the raw patient data is retrieved in [src/smart/SmartPatient.js](https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/blob/pilot/src/smart/SmartPatient.js) and where the CDS is applied in [src/hooks/useCds/index.js](https://github.com/ccsm-cds-tools/ccsm-cds-dashboard/blob/pilot/src/hooks/useCds/index.js), we need to call a function that reads all Observations in the `patientData`. For each one, it should look at their `value[x]` field. If they do not have a `valueCodeableConcept` but do have a `valueString`, we should call upon a JSON object that contains key-value pairs for text strings and associated SNOMED-CT codes. If there is a match in this JSON database, we should change the value field to a `valueCodeableConcept` with the new SNOMED code, and include the original text in the `text` field of the CodeableConcept.

**Comment by yunwwang** [comment]
solved
